spring.application.name=demo

#spring.cache.type=simple
#server.port=8080


spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
# spring.data.redis.password=yourpassword   # if Redis requires auth
# Optional: default TTL for cache entries (in ms)
spring.cache.redis.time-to-live=600000
spring.cache.redis.cache-null-values=false
